spring.application.name=backend

# Server
server.port=8080

# Datasource - MySQL (thay b?ng thông tin c?a b?n)
spring.datasource.url=jdbc:mysql://localhost:3306/management_intern?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456789A
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#MySQL Backend


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT - thay secret & expiration
app.jwt.secret=Z!8f@K#6pL$9qR%2uT^5xW&7yB*3cD(1)G_+mS
app.jwt.expiration-ms=86400000

# Other
spring.main.allow-bean-definition-overriding=true
